# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 143ced370bfd535330a82b4ae5295e1e1f0deb457f6cd9f0fdff92b49e9180d27118157ceaccdf73d3c64c793b56d0c1d5ebb14f115755f047d06c9b656303bd

test:
  secret_key_base: 7641927bbd9d45f2ac45ae7037e281b67d5d3049dde3eef72a964249e5590ee7a8bd9f70c1055f74cab9ba0ebdbb3e5f75ba1b43b8503fbd557e6537f8d21837

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
